/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewsRouteImport } from './routes/news'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as EquitiesRouteImport } from './routes/equities'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const EquitiesRoute = EquitiesRouteImport.update({
  id: '/equities',
  path: '/equities',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/crypto': typeof CryptoRoute
  '/equities': typeof EquitiesRoute
  '/holdings': typeof HoldingsRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/crypto': typeof CryptoRoute
  '/equities': typeof EquitiesRoute
  '/holdings': typeof HoldingsRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/crypto': typeof CryptoRoute
  '/equities': typeof EquitiesRoute
  '/holdings': typeof HoldingsRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/crypto'
    | '/equities'
    | '/holdings'
    | '/news'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/crypto'
    | '/equities'
    | '/holdings'
    | '/news'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assistant'
    | '/crypto'
    | '/equities'
    | '/holdings'
    | '/news'
    | '/settings'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  CryptoRoute: typeof CryptoRoute
  EquitiesRoute: typeof EquitiesRoute
  HoldingsRoute: typeof HoldingsRoute
  NewsRoute: typeof NewsRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equities': {
      id: '/equities'
      path: '/equities'
      fullPath: '/equities'
      preLoaderRoute: typeof EquitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  CryptoRoute: CryptoRoute,
  EquitiesRoute: EquitiesRoute,
  HoldingsRoute: HoldingsRoute,
  NewsRoute: NewsRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
